"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['passwordManager.py']
APP_NAME = "PasswordManager"
DATA_FILES = ['password.sqlite']
OPTIONS = {
    'iconfile': '/Users/mj-consult/Projects/python-lessons/lesson-2/images/pass-manager.icns',
    'plist': {
        'CFBundleName': APP_NAME,
        'CFBundleDisplayName': APP_NAME,
        'CFBundleGetInfoString': "Managing your passwords",
        'CFBundleVersion': "0.1.0",
        'CFBundleShortVersionString': "0.1.0",
        'NSHumanReadableCopyright': "Copyright © 2021, Michael Johnson, All Rights Reserved"
    }
}

setup(
    name=APP_NAME,
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
    version='1.0',
    description='Managing your passwords',
    author='Michael Johnson',
    author_email='mcangelo200@gmail.com',
    url='https://www.codeAfric.com',
    
)
